# Generated by Django 4.2.30 on 2026-08-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_issueproperty_issuepropertyoption_issuepropertyvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectissuetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
