# Generated by Django 4.2.30 on 2026-08-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_projectissuetype_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issueproperty',
            name='issue_property_unique_issue_type_name_when_deleted_at_null',
        ),
        migrations.AlterUniqueTogether(
            name='issueproperty',
            unique_together={('issue_type', 'display_name', 'project', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='issueproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', True)), fields=('issue_type', 'display_name'), name='issue_property_unique_shared_name_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='issueproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', False)), fields=('issue_type', 'display_name', 'project'), name='issue_property_unique_project_name_when_deleted_at_null'),
        ),
    ]
