# Generated by Django 5.2.15 on 2026-08-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
        ('db', '0124_remove_issueproperty_issue_property_unique_issue_type_name_when_deleted_at_null_and_more'),
    ]

    operations = [
    ]
