# Generated by Django 5.2.15 on 2026-08-13 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_merge_20260813_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubBranchLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('repository_id', models.BigIntegerField()),
                ('repo_full_name', models.CharField(max_length=500)),
                ('branch_name', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_branches', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Github Branch Link',
                'verbose_name_plural': 'Github Branch Links',
                'db_table': 'github_branch_links',
                'ordering': ('-created_at',),
                'unique_together': {('issue', 'repository_id', 'branch_name', 'deleted_at')},
            },
        ),
        migrations.CreateModel(
            name='GithubProjectSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('automation', models.JSONField(default=dict)),
                ('branch_format', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Github Project Settings',
                'verbose_name_plural': 'Github Project Settings',
                'db_table': 'github_project_settings',
                'ordering': ('-created_at',),
                'unique_together': {('project', 'deleted_at')},
            },
        ),
        migrations.CreateModel(
            name='GithubPullRequestLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('repository_id', models.BigIntegerField()),
                ('repo_full_name', models.CharField(max_length=500)),
                ('pr_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('url', models.URLField(blank=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=20)),
                ('review_state', models.CharField(blank=True, max_length=30)),
                ('checks_state', models.CharField(blank=True, max_length=30)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('author_avatar', models.URLField(blank=True)),
                ('source_branch', models.CharField(blank=True, max_length=500)),
                ('target_branch', models.CharField(blank=True, max_length=500)),
                ('link_type', models.CharField(choices=[('closing', 'Closing'), ('reference', 'Reference'), ('relation', 'Relation'), ('manual', 'Manual')], default='reference', max_length=20)),
                ('last_event_at', models.DateTimeField(null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_pull_requests', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Github Pull Request Link',
                'verbose_name_plural': 'Github Pull Request Links',
                'db_table': 'github_pull_request_links',
                'ordering': ('-created_at',),
                'unique_together': {('issue', 'repository_id', 'pr_number', 'deleted_at')},
            },
        ),
    ]
