# Generated by Django 5.2.15 on 2026-08-15 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_github_integration_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('title_prefix', models.CharField(max_length=255)),
                ('duration_weeks', models.PositiveIntegerField(default=2)),
                ('cooldown_days', models.PositiveIntegerField(default=0)),
                ('next_start_date', models.DateField()),
                ('upcoming_count', models.PositiveSmallIntegerField(default=1)),
                ('auto_rollover', models.BooleanField(default=False)),
                ('next_sequence', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Cycle Schedule',
                'verbose_name_plural': 'Cycle Schedules',
                'db_table': 'cycle_schedules',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project',), name='cycle_schedule_unique_project_when_deleted_at_null')],
                'unique_together': {('project', 'deleted_at')},
            },
        ),
    ]
