# Generated by Django 5.2.15 on 2026-08-15 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_cycle_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='progress_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='CycleProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('scope', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('backlog', models.PositiveIntegerField(default=0)),
                ('unstarted', models.PositiveIntegerField(default=0)),
                ('started', models.PositiveIntegerField(default=0)),
                ('cancelled', models.PositiveIntegerField(default=0)),
                ('total_estimate_points', models.FloatField(default=0)),
                ('completed_estimate_points', models.FloatField(default=0)),
                ('backlog_estimate_points', models.FloatField(default=0)),
                ('unstarted_estimate_points', models.FloatField(default=0)),
                ('started_estimate_points', models.FloatField(default=0)),
                ('cancelled_estimate_points', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='db.cycle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Cycle Progress',
                'verbose_name_plural': 'Cycle Progress',
                'db_table': 'cycle_progress',
                'ordering': ('date',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('cycle', 'date'), name='cycle_progress_unique_cycle_date_when_deleted_at_null')],
                'unique_together': {('cycle', 'date', 'deleted_at')},
            },
        ),
    ]
