# Generated by Django 5.2.15 on 2026-09-03 23:18

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_cycle_progress_module_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTypeProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('default_value', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('sort_order', models.FloatField(default=65535)),
            ],
            options={
                'verbose_name': 'Issue Type Property',
                'verbose_name_plural': 'Issue Type Properties',
                'db_table': 'issue_type_properties',
                'ordering': ('sort_order',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='issueproperty',
            name='issue_property_unique_shared_name_when_deleted_at_null',
        ),
        migrations.RemoveConstraint(
            model_name='issueproperty',
            name='issue_property_unique_project_name_when_deleted_at_null',
        ),
        migrations.AlterUniqueTogether(
            name='issueproperty',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='issueproperty',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issueproperty',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='db.issuetype'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='issue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_links', to='db.issuetype'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_links', to='db.issueproperty'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='issuetypeproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'issue_type', 'property'), name='issue_type_property_unique_link_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='issuetypeproperty',
            unique_together={('project', 'issue_type', 'property', 'deleted_at')},
        ),
    ]


# ---------------------------------------------------------------------------
# Data migration: every existing type-bound property becomes a library
# definition attached through links. Shared properties (project NULL) get a
# link for every project using the type; project-scoped ones get one link.
# Values are untouched (they already reference the property id).
# ---------------------------------------------------------------------------
from django.db import migrations as _migrations  # noqa: E402


def forwards_property_links(apps, schema_editor):
    IssueProperty = apps.get_model("db", "IssueProperty")
    IssueTypeProperty = apps.get_model("db", "IssueTypeProperty")
    ProjectIssueType = apps.get_model("db", "ProjectIssueType")

    for prop in IssueProperty.objects.filter(deleted_at__isnull=True, issue_type__isnull=False):
        if prop.project_id:
            project_ids = [prop.project_id]
        else:
            project_ids = list(
                ProjectIssueType.objects.filter(
                    issue_type_id=prop.issue_type_id, deleted_at__isnull=True
                ).values_list("project_id", flat=True)
            )
        for project_id in project_ids:
            IssueTypeProperty.objects.get_or_create(
                project_id=project_id,
                issue_type_id=prop.issue_type_id,
                property_id=prop.id,
                deleted_at=None,
                defaults={
                    "workspace_id": prop.workspace_id,
                    "is_required": prop.is_required,
                    "is_active": prop.is_active,
                    "default_value": list(prop.default_value or []),
                    "sort_order": prop.sort_order,
                    "created_by_id": prop.created_by_id,
                    "updated_by_id": prop.updated_by_id,
                },
            )
        # Definitions live in the library now; project scope is expressed by links.
        prop.issue_type_id = None
        prop.project_id = None
        prop.save(update_fields=["issue_type", "project"])


def backwards_property_links(apps, schema_editor):
    # Links are dropped by the schema reversal; definitions keep their data.
    pass


Migration.operations.append(_migrations.RunPython(forwards_property_links, backwards_property_links))
